# Generated by Django 3.2.10 on 2021-12-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=70)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=200)),
                ('addressStreet', models.CharField(default='', max_length=40)),
                ('addressNumber', models.CharField(default='', max_length=8)),
                ('addressCity', models.CharField(default='', max_length=20)),
                ('addressState', models.CharField(default='', max_length=2)),
                ('password', models.CharField(default='1234', max_length=32)),
            ],
        ),
    ]
